#!/bin/make
#SCANOR
FORT_OBJS = set2cc.o messlog.o mildatim.o scanor.o

#Decoding for the Pixie16 List Mode Events
CXX_OBJS = ReadBuffDataA.o ReadBuffDataD.o ReadBuffDataF.o

#XML Parsing
CXX_OBJS += pugixml.o

#Core
CXX_OBJS += PixieStd.o BarBuilder.o Calibrator.o ChanEvent.o DetectorDriver.o\
    DetectorLibrary.o DetectorSummary.o EventProcessor.o Globals.o Identifier.o\
    Initialize.o Messenger.o Notebook.o RandomPool.o RawEvent.o StatsData.o \
    TimingCalibrator.o TimingMapBuilder.o WalkCorrector.o

#Correlation
CXX_OBJS += PlaceBuilder.o Places.o TreeCorrelator.o

#Plotting
CXX_OBJS += Plots.o PlotsRegister.o

#Trace Analysis
CXX_OBJS += CfdAnalyzer.o DoubleTraceAnalyzer.o FittingAnalyzer.o TauAnalyzer.o\
    Trace.o TraceExtractor.o TraceFilterer.o TraceAnalyzer.o WaaAnalyzer.o \
    WaveformAnalyzer.o

#Processors
CXX_OBJS += BetaScintProcessor.o DoubleBetaProcessor.o \
    GeProcessor.o GeCalibProcessor.o Hen3Processor.o \
    IonChamberProcessor.o LiquidScintProcessor.o LogicProcessor.o \
    NeutronScintProcessor.o PositionProcessor.o RootProcessor.o \
    PulserProcessor.o PspmtProcessor.o SsdProcessor.o TeenyVandleProcessor.o \
    TemplateProcessor.o VandleProcessor.o

#Experiment Processors
CXX_OBJS += IS600Processor.o
