#@authors K. Smith
include_directories(include)
add_subdirectory(source)

install(
    FILES ${CMAKE_CURRENT_SOURCE_DIR}/send_alarm
    FILES ${CMAKE_CURRENT_SOURCE_DIR}/send_elog
    FILES ${CMAKE_CURRENT_SOURCE_DIR}/send_elog
    PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    DESTINATION bin)

install( 
    FILES ${CMAKE_CURRENT_SOURCE_DIR}/POLL2_ELOG_SETTINGS
    PERMISSIONS OWNER_WRITE OWNER_READ  GROUP_READ  WORLD_READ
    DESTINATION bin)
    
