#!/bin/bash
#@authors T. T. King (2019), D. Miller

if [ -z $1 ]; then
    EMAIL="tking36@vols.utk.edu"
else
    EMAIL=$1
fi

echo "poll2 on ${HOSTNAME} has entered into an ERROR state. This requires human attention. " | mail -s "${HOSTNAME}:poll2 alert" ${EMAIL}
