#!/bin/bash
#@authors T. T. King (2019), D. Miller

if [ -z $1 ]; then
    EMAIL="tking.91@gmail.com"
else
    EMAIL=$1
fi

if [ ! -z ${EMAIL_FQDN_CHEAT} ]; then 
    COMP_HOST_NAME=${EMAIL_FQDN_CHEAT} 
else 
    COMP_HOST_NAME=${HOSTNAME}
fi

if [ ! -z ${EMAIL_FROM_USER} ] && [ ! -z ${EMAIL_FQDN_CHEAT} ];then
    FROM_ADDRESS_CMD="-S from=\"${EMAIL_FROM_USER}\""
else
    FROM_ADDRESS_CMD=""
fi

EMAIL_BODY="poll2 on ${COMP_HOST_NAME} has entered into an ERROR state. This requires human attention." 

echo "${EMAIL_BODY}" | mailx ${FROM_ADDRESS_CMD} -s "${HOSTNAME}:poll2 alert" ${EMAIL}
